# Generated by Django 4.1.2 on 2022-10-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackuser', '0002_alter_slackuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='username',
            new_name='slack_username',
        ),
    ]
