# Generated by Django 4.1.2 on 2022-10-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackuser', '0003_rename_username_slackuser_slack_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='slack_username',
            new_name='slackUsername',
        ),
    ]
