# Generated by Django 4.1.2 on 2022-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackuser', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='BIO',
            field=models.TextField(blank=True),
        ),
    ]
