# Generated by Django 4.1.2 on 2022-11-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackuser', '0006_alter_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentClass',
            field=models.CharField(choices=[('PR1', 'Primary One'), ('PR2', 'Primary Two'), ('PR3', 'Primary Three')], max_length=150, null=True),
        ),
    ]
